services:
  redpanda:
    image: redpandadata/redpanda:v23.2.3
    hostname: redpanda
    container_name: hadi-redpanda
    ports:
      - "0.0.0.0:9092:9092"
      - "0.0.0.0:29092:29092"
    command:
      - redpanda
      - start
      - --overprovisioned
      - --smp
      - "3"
      - --memory
      - "8G"
      - --reserve-memory
      - "0M"
      - --set
      - redpanda.cluster_id=turning-red
      - --set
      - redpanda.enable_idempotence=true
      - --set
      - redpanda.enable_transactions=true
      - --set
      - redpanda.auto_create_topics_enabled=true
      - --node-id
      - "0"
      - --kafka-addr
      - PLAINTEXT://0.0.0.0:29092,OUTSIDE://0.0.0.0:9092
      - --advertise-kafka-addr
      - PLAINTEXT://redpanda:29092,OUTSIDE://redpanda:9092
      - --check=false
    mem_limit: 8g
    cpus: 3.0
    healthcheck:
      test: ["CMD", "rpk", "cluster", "health"]
      interval: 10s
      retries: 5

  connect:
    container_name: saint-connector
    build:
      context: .
    depends_on:
      - redpanda
    ports:
      - "0.0.0.0:8083:8083"
    environment:
      BOOTSTRAP_SERVERS: "redpanda:9092"
      GROUP_ID: "1"
      CONFIG_STORAGE_TOPIC: "ourdb.configs"
      OFFSET_STORAGE_TOPIC: "ourdb.offset"
      STATUS_STORAGE_TOPIC: "ourdb.status"
      KEY_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      VALUE_CONVERTER: "io.confluent.connect.avro.AvroConverter"
      KEY_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      VALUE_CONVERTER_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      INTERNAL_KEY_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
      INTERNAL_VALUE_CONVERTER: "org.apache.kafka.connect.json.JsonConverter"
    volumes:
      - ./debezium-connector-clickhouse:/kafka/manual
    mem_limit: 8g
    cpus: 4.0
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8083"]
      interval: 10s
      retries: 5

  mariadb:
    image: mariadb:10.6
    container_name: saint-mariadb
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: saint
      MYSQL_PASSWORD: saint_123
      MYSQL_ROOT_HOST: '%'
    volumes:
      - ./mysql_data:/var/lib/mysql
    command: --binlog-format=ROW --log-bin=/var/lib/mysql/mysql-bin.log --server-id=1 --innodb-buffer-pool-size=8G
    mem_limit: 10g
    cpus: 2.0
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost", "-uroot", "-proot"]
      interval: 10s
      retries: 0

  schema-registry:
    image: confluentinc/cp-schema-registry:7.3.0
    hostname: schema-registry
    container_name: saint-registry
    depends_on:
      - redpanda
    ports:
      - "0.0.0.0:8081:8081"
    environment:
      SCHEMA_REGISTRY_HOST_NAME: schema-registry
      SCHEMA_REGISTRY_KAFKASTORE_BOOTSTRAP_SERVERS: "redpanda:9092"
    mem_limit: 1g
    cpus: 0.5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8081"]
      interval: 10s
      retries: 5

  ksqldb-server:
    image: confluentinc/ksqldb-server:0.27.1
    hostname: ksqldb-server
    container_name: saint-ksqldb
    depends_on:
      - redpanda
      - schema-registry
    ports:
      - "0.0.0.0:8088:8088"
    environment:
      KSQL_LISTENERS: "http://0.0.0.0:8088"
      KSQL_BOOTSTRAP_SERVERS: "redpanda:9092"
      KSQL_KSQL_SCHEMA_REGISTRY_URL: "http://schema-registry:8081"
      KSQL_KSQL_LOGGING_PROCESSING_STREAM_AUTO_CREATE: "true"
      KSQL_KSQL_LOGGING_PROCESSING_TOPIC_AUTO_CREATE: "true"
      KSQL_KSQL_CONNECT_URL: "http://connect:8083"
    mem_limit: 2g
    cpus: 1.5
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8088/info"]
      interval: 10s
      retries: 5

  clickhouse:
    image: clickhouse/clickhouse-server
    container_name: saint-clickhouse
    environment:
      CLICKHOUSE_USER: saint
      CLICKHOUSE_PASSWORD: saint_123
    volumes:
      - ./ch_data:/var/lib/clickhouse/
      - ./ch_logs:/var/log/clickhouse-server/
    ports:
      - "0.0.0.0:9000:9000"
      - "0.0.0.0:8123:8123"
    ulimits:
      nproc: 65535
      nofile:
        soft: 262144
        hard: 262144
    mem_limit: 32g
    cpus: 7.0
    healthcheck:
      test: ["CMD-SHELL", "wget -qO- http://saint:saint_123@localhost:8123/ping"]
      interval: 10s
      retries: 0

  console:
    image: redpandadata/console:latest
    container_name: redpanda-console
    ports:
      - "0.0.0.0:8080:8080"
    environment:
      - KAFKA_BROKERS=redpanda:9092
      - KAFKA_SCHEMAREGISTRY_ENABLED=true
      - KAFKA_SCHEMAREGISTRY_URLS=http://schema-registry:8081
    command:
      - /app/console
      - --listen-addr=0.0.0.0:8080
    mem_limit: 1g
    cpus: 0.1

